### ISSUE TITLE
Update position inside strategy

### ISSUE THREAD

**Issue by HareHunter96** [tradalize/core#19]
Would be great to add possibility to update current position (add new order to average)
For now, found only this

`this.openOnNext = POSITION_DIRECTION.Long;`
`this.closeOnNext = true;`

**Comment by Besmerch123** [comment]
Hi!

Sorry for the delayed answer. 

Yeah, seems reasonable. I'll take a look when I can do that.

**Comment by Besmerch123** [comment]
Hello, @HareHunter96 
Excuse me one more time for the delayed response. 

I tried to find a workaround for your request and I have some concerns about it. 

I designed this system to be "position-size-agnostic", it doesn't store any information about position sizes anywhere in the memory. It is done to make it lightweight and more flexible in terms of post-analysis of trades. After the backtest you have an array of trades and you can calculate any position size with any property after that. 

When we average we have to calculate a weighted average of the position, so we kind of need some position size property. But I would not add it, at least for now. 

But now inside the `update` method of the strategy you have access to your `broker` instance, which contains a `currentPosition` property which you can modify if you need it. 
You can even add an additional `positionSize` property to the strategy or position itself (you only have to cast types) and calc your average on it.

So... I would not add averaging as one of the supported trading techniques at least for now, but you will have all the tools if you need to implement one. 

Also, as this is an open-source project - feel free to contribute and add such an opportunity, I will be glad to review it. 

Wish you the best and have a profitable trading!
